### PR TITLE
add new dashboard

### PR DESCRIPTION
**Pull request by antho1404**
## To run it

Run `npm run dev` in the server directory and another `npm run dev` at the root of the project

## List of resources

Services:
- `/services/`
- `/services/:hash`

Executions: (real time)
- `/executions`
- `/executions/:hash`

Instances:
- `/instances`
- `/instances/:hash`

Runners:
- `/runners`
- `/runners/:hash`

Processes:
- `/processes`
- `/processes/:hash`

### CODE REVIEW

**Comment by NicolasMahe** [comment]
@antho1404 what is the status on this?

**Comment by antho1404** [comment]
Except the conflicts to fix, it's ready for review. Not deployed anywhere yet so now has to be tested locally and we need to decide if we put that on marketplace.mesg.com or we release it as another website or create a dashboard application etc... but technically everything is here

**Comment by antho1404** [comment]
Docker image deployed, you can test it with the following
```
docker service create --network engine -p 5000:5000 --env ENGINE_ENDPOINT=engine:50052 mesg/dashboard:feature-dashboard
```

**Review by NicolasMahe — APPROVED** [review]
🍾 🎊

**Comment by NicolasMahe** [comment]
Let's also rename this repo to `dashboard`

**Pull request merged**
